# If you want to evaluate numeric expressions in this yaml file, just enclose your expression with
# '&'. In that simple expressions you can use the python math module.

# IMPORTANT: if adding new categories to the internal phobos, also change the
# visual representation of these in the add_motor Operator!

# Currently, these motors are only supported by MARS:
# generic_dc
# generic_bldc
# limes_typ1
# limes_typ2
# limes_typ3

motors:
    # generic motors
    generic_bldc:
        general:
            type: bldc
            shape: resource://dc
            size:
                - 0.2
                - 36
            categories:
                - generic
        controller: pid
        maxSpeed: 3.141
        maxEffort: 50.0
    generic_dc:
        general:
            type: dc
            shape: resource://dc
            size:
                - 0.2
                - 36
            categories:
                - generic
        controller: dc
        maxSpeed: 3.141
        maxEffort: 50.0
    # limes motors
    limes_typ1:
        general:
            type: bldc
            shape: resource://dc
            size:
                - 0.2
                - 36
            categories:
                - bldc
                - limes
        controller: limes_position
        maxSpeed: 1.438
        maxEffort: 238
        protocol: ndlcom
    limes_typ2:
        general:
            type: bldc
            shape: resource://dc
            size:
                - 0.2
                - 36
            categories:
                - bldc
                - limes
        controller: limes_position
        maxSpeed: 1.966
        maxEffort: 92
        protocol: ndlcom
    limes_typ3:
        general:
            type: bldc
            shape: resource://dc
            size:
                - 0.2
                - 36
            categories:
                - bldc
                - limes
        controller: limes_position
        maxSpeed: 2.293
        maxEffort: 54
        protocol: ndlcom
