# -------------------------------------------------------------------------------
# This file is part of Phobos, a Blender Add-On to edit robot models.
# Copyright (C) 2020 University of Bremen & DFKI GmbH Robotics Innovation Center
#
# You should have received a copy of the 3-Clause BSD License in the LICENSE file.
# If not, see <https://opensource.org/licenses/BSD-3-Clause>.
# -------------------------------------------------------------------------------

# This file holds definitions of submodel types.

submodeltypes:
  mechanism:
    definitions:
      dummy: 'dummy'
      # here go informations that will be custom properties of the group
    interfaces:
      dummy: 'dummy'
      # here we add the interface definitions which will end up in the
      # interface group
