# -------------------------------------------------------------------------------
# This file is part of Phobos, a Blender Add-On to edit robot models.
# Copyright (C) 2020 University of Bremen & DFKI GmbH Robotics Innovation Center
#
# You should have received a copy of the 3-Clause BSD License in the LICENSE file.
# If not, see <https://opensource.org/licenses/BSD-3-Clause>.
# -------------------------------------------------------------------------------

# If you want to evaluate numeric expressions in this yaml file, just enclose your expression with
# '&'. In that simple expressions you can use the python math module.

# IMPORTANT: if adding new categories to the internal phobos, also change the
# visual representation of these in the add_controller Operator!

# Currently, these controllers are only supported by MARS:
# pid
# dc
# limes_position
#
# For completeness we added:
# bldc

controllers:
    # generic controllers
    pid:
        general:
            type: PID
            shape: resource://pid
            size: 0.2
            categories:
                - generic
                - motor
        p: 20.0
        i: 1.0
        d: 0.1
    direct:
        general:
            type: direct
            shape: resource://direct
            size: 0.2
            categories:
                - generic
                - motor
    bldc:
        general:
            type: BLDC
            shape: resource://bldc
            size: 0.2
            categories:
                - generic
                - motor
        torque_constant: 1.
        speed_constant: 1.

    # MARS controllers
    limes_position:
        general:
            type: limes_position
            shape: resource://generic
            size: 0.2
            categories:
                - generic
                - motor
        p: 20.0
        i: 0.1
        d: 0.0
