# -------------------------------------------------------------------------------
# This file is part of Phobos, a Blender Add-On to edit robot models.
# Copyright (C) 2018 University of Bremen & DFKI GmbH Robotics Innovation Center

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# -------------------------------------------------------------------------------

model:
    sensors:
        $forElem:
            type:
                required: true
                default: 'CameraSensor'
            $selection__type: {} #will be generated by phobos
    geometry:
        isReference: true
        type:
            required: true
            default: 'box'
        $selection__type:
            box:
                size:
                    required: true
                    default: [1.0, 1.0, 1.0]
            sphere:
                radius:
                    required: true
                    default: 1.0
            cylinder:
                radius:
                    required: true
                    default: 1.0
                length:
                    required: true
                    default: 1.0
            plane:
                size:
                    required: true
                    default: [1.0, 1.0]
            mesh:
                filename:
                    required: true
                    default: 'meshFileName'
    pose:
        isReference: true
        matrix:
            required: true
            default:
                - [0.0, 0.0, 0.0, 0.0]
                - [0.0, 0.0, 0.0, 0.0]
                - [0.0, 0.0, 0.0, 0.0]
                - [0.0, 0.0, 0.0, 0.0]
        rotation_euler:
            required: true
            default: [0.0, 0.0, 0.0]
        rotation_quaternion:
            required: true
            default: [0.0, 0.0, 0.0]
        translation:
            required: true
            default: [0.0, 0.0, 0.0]
    links:
        $forElem:
            approxcollision:
                required: true
                default: []
            name:
                required: true
                default: 'linkName'
            $reference: pose
            visual:
                $forElem:
                    name:
                        required: true
                        default: 'visualName'
                    $reference: geometry
                    $reference: pose
            inertial:
                inertia:
                    required: true
                    default: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
                mass:
                    required: true
                    default: 1.0
                name:
                    required: true
                    default: 'inertialName'
                $reference: pose
            collision:
                $forElem:
                    name:
                        required: true
                        default: 'collisionName'
                    $reference: pose
                    $reference: geometry
    joints:
        $forElem:
            state:
                matrix:
                    required: true
                    default:
                        - [1.0, 0.0, 0.0, 0.0]
                        - [0.0, 1.0, 0.0, 0.0]
                        - [0.0, 0.0, 1.0, 0.0]
                        - [0.0, 0.0, 0.0, 1.0]
                rotation_euler:
                    required: true
                    default: [0.0, 0.0, 0.0]
                rotation_quaternion:
                    required: true
                    default: [1.0, 0.0, 0.0, 0.0]
                translation:
                    required: true
                    default: [0.0, 0.0, 0.0]
            child:
                required: true
                default: 'jointChild'
            name:
                required: true
                default: 'jointName'
            parent:
                required: true
                default: 'jointParent'
            type:
                required: true
                default: 'floating'
