# -------------------------------------------------------------------------------
# This file is part of Phobos, a Blender Add-On to edit robot models.
# Copyright (C) 2018 University of Bremen & DFKI GmbH Robotics Innovation Center

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# -------------------------------------------------------------------------------

materials:
    phobos_joint:
        diffuse: [0, 0, 1, 1]
        specular: [1, 1, 1, 1]
        diffuse_intensity: 1.0
    phobos_name:
        diffuse: [1, 1, 1, 1]
        specular: [1, 1, 1, 1]
        diffuse_intensity: 1.0
    phobos_laserscanner:
        diffuse: [1.0, 0.08, 0.08, 0.3]
        specular: [1, 1, 1, 0.3]
        alpha: 0.3
        diffuse_intensity: 1.0
    phobos_tof-camera:
        diffuse: [0.44, 1, 0.735, 0.3]
        specular: [1, 1, 1, 0.3]
        diffuse_intensity: 0.7
    phobos_inertial:
        diffuse: [1, 0.18, 0, 1]
        specular: [1, 1, 1, 1]
        diffuse_intensity: 1.0
    phobos_sensor:
        diffuse: [0.8, 0.75, 0, 1]
        specular: [1, 1, 1, 1]
        diffuse_intensity: 1.0
    phobos_controller:
        diffuse: [0.518, 0.364, 0.8, 0.3]
        specular: [1, 1, 1, 0.3]
        diffuse_intensity: 0.7
    phobos_indicator1:
        diffuse: [1, 0, 0, 1]
        specular: [1, 1, 1, 1]
        diffuse_intensity: 1.0
    phobos_indicator2:
        diffuse: [0, 1, 0, 1]
        specular: [1, 1, 1, 1]
        diffuse_intensity: 1.0
    phobos_indicator3:
        diffuse: [0, 0, 1, 1]
        specular: [1, 1, 1, 1]
        diffuse_intensity: 1.0
    phobos_indicator4:
        diffuse: [1, 0, 1, 1]
        specular: [1, 1, 1, 1]
        diffuse_intensity: 1.0
    phobos_indicator5:
        diffuse: [1, 1, 0, 1]
        specular: [1, 1, 1, 1]
        diffuse_intensity: 1.0
    phobos_indicator6:
        diffuse: [0, 1, 1, 1]
        specular: [1, 1, 1, 1]
        diffuse_intensity: 1.0
    phobos_error:
        diffuse: [1, 0, 0, 0.5]
        specular: [1, 1, 1, 0.5]
        diffuse_intensity: 1.0
