# -------------------------------------------------------------------------------
# This file is part of Phobos, a Blender Add-On to edit robot models.
# Copyright (C) 2018 University of Bremen & DFKI GmbH Robotics Innovation Center

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# -------------------------------------------------------------------------------

# This file holds definitions of (sub)mechanisms commonly used in the
# construction of robots, such as parallel mechanisms for joint actuation.

submechanisms:
  revolute:
    type: R
    joints:
        active: ['revolute']
        independent: ['revolute']
        spanningtree: ['revolute']
  universal:
    type: RR
    joints:
        active: ['revolute1', 'revolute2']
        independent: ['revolute1', 'revolute2']
        spanningtree: ['revolute1', 'revolute2']
  spherical:
    type: RRR
    joints:
        active: ['revolute1', 'revolute2', 'revolute3']
        independent: ['revolute1', 'revolute2', 'revolute3']
        spanningtree: ['revolute1', 'revolute2', 'revolute3']
  lambda_mechanism:
    type: rrPr
    joints:
        active: ['prismatic1']
        independent: ['revolute1']
        spanningtree: ['revolute1', 'revolute2', 'prismatic1']
  2SPRR+1U:
    type: 2sPrr+1u
    joints:
        active: ['prismatic7', 'prismatic10']
        independent: ['revolute1', 'revolute2']
        spanningtree: ['revolute1', 'revolute2', 'revolute3', 'revolute4', 'revolute5', 'revolute6', 'prismatic7', 'revolute8', 'revolute9', 'prismatic10']
  2SPU+1U:
    type: 2sPu+1u
    joints:
        active: ['prismatic5', 'prismatic8']
        independent: ['revolute1', 'revolute2']
        spanningtree: ['revolute1', 'revolute2', 'revolute3', 'revolute4', 'prismatic5', 'revolute6', 'revolute7', 'prismatic8']
